import { Playfair_Display, Open_Sans } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "../../i18n/routing";
import ThemeProvider from "@/provider/ThemeProvider";
import Header from "@/components/web/Header";
import Footer from "@/components/web/Footer";


import "./globals.css";

export async function generateStaticParams() {
  return routing.locales.map((l) => ({ locale: l }));
}


const PlayfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  preload: false
});
const OpenSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  preload: false
});

// const trirong = Trirong({
//   variable: "--font-trirong",
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   preload: false
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const messages = await getMessages();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` select-none ${PlayfairDisplay.variable} ${OpenSans.variable} antialiased sm:overflow-x-hidden bg-background text-foreground`}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
